services:
  - type: static
    name: dionisio-perfumeria
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
